// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGL4Y1q88_HWAX3mjsxi_AgOwM1kJsnck',
    appId: '1:245940513411:web:307769ec4227869b8409b6',
    messagingSenderId: '245940513411',
    projectId: 'together-d1575',
    authDomain: 'together-d1575.firebaseapp.com',
    storageBucket: 'together-d1575.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP-49_WJfIC3rd9Yp2uF0shKSHKORsjOQ',
    appId: '1:245940513411:android:4831f952f3da63e78409b6',
    messagingSenderId: '245940513411',
    projectId: 'together-d1575',
    storageBucket: 'together-d1575.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCatQNC_MmYKMAm-zMmDyYiyTpmbPSTqdw',
    appId: '1:245940513411:ios:ce8525a8bed12e1f8409b6',
    messagingSenderId: '245940513411',
    projectId: 'together-d1575',
    storageBucket: 'together-d1575.appspot.com',
    iosClientId: '245940513411-us2ntmde5ih349f0jgb76r36ti5kg6a2.apps.googleusercontent.com',
    iosBundleId: 'com.example.together',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCatQNC_MmYKMAm-zMmDyYiyTpmbPSTqdw',
    appId: '1:245940513411:ios:ce8525a8bed12e1f8409b6',
    messagingSenderId: '245940513411',
    projectId: 'together-d1575',
    storageBucket: 'together-d1575.appspot.com',
    iosClientId: '245940513411-us2ntmde5ih349f0jgb76r36ti5kg6a2.apps.googleusercontent.com',
    iosBundleId: 'com.example.together',
  );
}
